@baseUrl = http://localhost:3000

# PESSOAS
### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "b@a.com",
  "password": "123456",
  "nome": "Laura"
}

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/recados/4/
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "Recado amistoso",
  "deId": 8,
  "paraId": 3
}
### Atualiza um recado
PATCH {{baseUrl}}/recados/8/
Content-Type: application/json

{
  "texto": "Recado",
  "lido": true
}
### Apaga um recado
DELETE {{baseUrl}}/recados/2/

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/
